version: "3.8"

services:
    web:
        build:
            context: client-web
            dockerfile: Dockerfile.web
        ports:
            - 8081:80

    api:
        build:
            context: server-api
            dockerfile: Dockerfile.api
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: sleepywood
            # MYSQL_USER: mariadb
            # MYSQL_PASSWORD: mariadb
            MYSQL_HOST: db
            MYSQL_PORT: 3306
            REDIS_HOST: redis
            REDIS_PORT: 6379
            PORT: 3000
            # SECRET: abcd
            # SALT: 1234
            # WEATHER_API_KEY: 1234
            THROTTLE_TTL: 60
            THROTTLE_LIMIT: 1000
            TZ: Asia/Seoul
            locale: ko-KR
        depends_on:
            - db
            - redis
            - web

    db:
        image: mariadb:10
        restart: unless-stopped
        volumes:
            - mariadb-data:/var/lib/mysql
        environment:
            # MYSQL_ROOT_PASSWORD: mariadb
            MYSQL_DATABASE: sleepywood
            # MYSQL_USER: mariadb
            # MYSQL_PASSWORD: mariadb

    redis:
        image: redis:7
        restart: unless-stopped

volumes:
    mariadb-data:
